import type { QuestionDefinition } from "@/types/quiz";

export const defaultQuestions: QuestionDefinition[] = [
  {
    id: "primary-interest",
    slug: "interesse-principal",
    version: 1,
    title: "Quais temas previdenciários motivaram sua análise?",
    description:
      "Selecione uma ou mais opções para orientar a triagem inicial.",
    type: "checkbox",
    required: true,
    options: [
      { value: "aposentadoria", label: "Aposentadoria" },
      { value: "incapacidade", label: "Benefício por incapacidade" },
      { value: "assistencial", label: "Benefício assistencial" },
      { value: "pensao", label: "Pensão ou benefício familiar" },
    ],
    validations: {
      minSelections: 1,
      message: "Selecione ao menos uma opção.",
    },
    answerStateOptions: ["unknown"],
    benefits: ["aposentadoria", "incapacidade", "assistencial"],
    next: "birth-date",
    active: true,
    order: 10,
  },
  {
    id: "birth-date",
    slug: "data-nascimento",
    version: 1,
    title: "Qual é a sua data de nascimento?",
    description:
      "Essa informação é usada apenas para organizar a triagem por faixa etária. A idade isoladamente não confirma direito a benefício.",
    type: "date",
    required: true,
    answerStateOptions: ["unknown", "withheld"],
    benefits: ["aposentadoria", "assistencial"],
    previous: "primary-interest",
    next: "currently-working",
    active: true,
    order: 20,
  },
  {
    id: "currently-working",
    slug: "trabalha-atualmente",
    version: 1,
    title: "Você trabalha atualmente?",
    description:
      "Considere trabalho com carteira, autônomo, rural ou informal.",
    type: "boolean",
    required: true,
    answerStateOptions: ["unknown"],
    benefits: ["aposentadoria", "incapacidade"],
    previous: "birth-date",
    next: "work-type",
    active: true,
    order: 30,
  },
  {
    id: "work-type",
    slug: "tipo-trabalho",
    version: 1,
    title: "Qual alternativa descreve melhor sua atividade principal?",
    type: "radio",
    required: true,
    options: [
      { value: "clt", label: "Empregado com carteira assinada" },
      { value: "autonomo", label: "Autônomo ou contribuinte individual" },
      { value: "rural", label: "Trabalhador rural" },
      { value: "servidor", label: "Servidor público" },
      { value: "sem_atividade", label: "Não estou em atividade atualmente" },
    ],
    answerStateOptions: ["unknown", "withheld"],
    benefits: ["aposentadoria", "incapacidade"],
    previous: "currently-working",
    next: "contribution-years",
    active: true,
    order: 40,
  },
  {
    id: "contribution-years",
    slug: "anos-contribuicao",
    version: 1,
    title: "Quantos anos de contribuição você estima possuir?",
    description:
      "Informe uma estimativa. A conferência documental será tratada em etapa futura.",
    type: "number",
    required: true,
    placeholder: "Ex.: 12",
    validations: {
      min: 0,
      max: 60,
      message: "Informe um número entre 0 e 60.",
    },
    answerStateOptions: ["unknown"],
    benefits: ["aposentadoria"],
    previous: "work-type",
    next: "last-income",
    active: true,
    order: 50,
  },
  {
    id: "last-income",
    slug: "ultima-renda",
    version: 1,
    title: "Qual foi sua renda mensal aproximada mais recente?",
    description:
      "Resposta opcional. Use apenas uma estimativa aproximada; não anexe documentos nem informe dados de terceiros nesta etapa.",
    type: "currency",
    required: false,
    placeholder: "Ex.: 2500",
    validations: {
      min: 0,
      max: 100000,
      message: "Informe um valor válido.",
    },
    answerStateOptions: ["unknown", "withheld"],
    benefits: ["aposentadoria", "assistencial", "incapacidade"],
    previous: "contribution-years",
    next: "has-medical-condition",
    active: true,
    order: 60,
  },
  {
    id: "has-medical-condition",
    slug: "condicao-saude",
    version: 1,
    title: "Você possui alguma condição de saúde que dificulta o trabalho?",
    description:
      "Informe apenas se uma condição de saúde impacta sua rotina de trabalho. Não inclua diagnóstico, laudo ou detalhes médicos nesta etapa.",
    type: "boolean",
    required: true,
    answerStateOptions: ["unknown", "withheld"],
    benefits: ["incapacidade"],
    previous: "last-income",
    next: "additional-context",
    active: true,
    order: 70,
  },
  {
    id: "additional-context",
    slug: "contexto-adicional",
    version: 1,
    title: "Há alguma informação adicional que você considera importante?",
    description:
      "Descreva brevemente seu contexto. Evite inserir documentos, laudos, diagnósticos detalhados ou informações de terceiros.",
    type: "textarea",
    required: false,
    placeholder: "Conte em poucas linhas o que motivou sua busca.",
    validations: {
      maxLength: 1000,
      message: "Use no máximo 1000 caracteres.",
    },
    answerStateOptions: ["withheld"],
    benefits: ["aposentadoria", "incapacidade", "assistencial"],
    previous: "has-medical-condition",
    active: true,
    order: 80,
  },
];
