import type { QuizTemplateDefinition } from "@/types/quiz";

const platformPreventiveText = {
  shortDisclaimer:
    "O Radar Previdenciário organiza informações para uma triagem inicial. O resultado não confirma direito a benefício, não constitui parecer jurídico e pode depender de documentos e avaliação individual.",
  sensitiveDisclaimer:
    "Este módulo pode incluir informações sobre saúde ou situação familiar. Você pode escolher 'Não sei informar' ou 'Prefiro não informar'. A ferramenta não realiza diagnóstico médico nem avalia incapacidade.",
  resultDisclaimer:
    "O resultado é informativo, não confirma direito a benefício, não constitui parecer jurídico e depende de análise individual com documentos por profissional habilitado.",
};

export const generalQuizTemplate: QuizTemplateDefinition = {
  id: "11111111-1111-4111-8111-111111111111",
  slug: "geral",
  name: "Triagem previdenciária geral",
  description:
    "Porta de entrada para identificar o assunto previdenciário e organizar informações mínimas.",
  category: "previdenciario",
  audience: "Pessoas que buscam orientação inicial sobre tema previdenciário.",
  type: "general",
  source: "platform",
  ownership: "platform_managed",
  status: "active",
  version: 1,
  isDefault: true,
  completenessFields: [
    "general-main-situation",
    "general-inss-request",
    "general-affiliation",
  ],
  preventiveText: platformPreventiveText,
  result: {
    title: "Suas informações foram organizadas para uma triagem inicial",
    summary:
      "As respostas ajudam a identificar o assunto previdenciário relacionado e a prioridade operacional do atendimento. Esta triagem não confirma direito a benefício e pode depender de documentos e avaliação individual.",
    nextStep:
      "Você pode seguir com perguntas temáticas, encerrar a triagem ou solicitar contato do escritório.",
    topicLabel: "Triagem previdenciária geral",
  },
  questions: [
    {
      id: "general-main-situation",
      slug: "situacao-principal",
      version: 1,
      title: "Qual é a principal situação que motivou sua busca?",
      description:
        "Escolha a alternativa que melhor organiza o tema. Se não souber, use a opção de dúvida.",
      type: "radio",
      required: true,
      options: [
        { value: "retirement", label: "Aposentadoria" },
        { value: "disability", label: "Benefício por incapacidade" },
        { value: "maternity", label: "Salário-maternidade" },
        { value: "bpc", label: "BPC/LOAS" },
        { value: "death_pension", label: "Pensão por morte" },
        {
          value: "dependent_disability",
          label: "Benefício relacionado a dependente com deficiência",
        },
        { value: "denied_or_suspended", label: "Benefício negado ou suspenso" },
        { value: "rural_worker", label: "Trabalhador rural" },
        { value: "review", label: "Revisão de benefício" },
        { value: "other", label: "Outro tema" },
      ],
      answerStateOptions: ["unknown"],
      benefits: [
        "aposentadoria",
        "incapacidade",
        "salario-maternidade",
        "assistencial",
        "pensao",
        "autismo",
      ],
      next: "general-inss-request",
      active: true,
      order: 10,
    },
    {
      id: "general-inss-request",
      slug: "pedido-inss",
      version: 1,
      title: "Você já possui pedido no INSS relacionado a essa situação?",
      type: "radio",
      required: true,
      options: [
        { value: "pending", label: "Sim, está em análise" },
        { value: "approved", label: "Sim, foi aprovado" },
        { value: "denied", label: "Sim, foi negado" },
        { value: "ceased_or_suspended", label: "Sim, foi cessado ou suspenso" },
        { value: "not_requested", label: "Ainda não fiz pedido" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["aposentadoria", "incapacidade", "assistencial"],
      previous: "general-main-situation",
      next: "general-affiliation",
      active: true,
      order: 20,
    },
    {
      id: "general-affiliation",
      slug: "filiacao-inss",
      version: 1,
      title:
        "Você possui ou já possuiu contribuições, vínculo de emprego, atividade rural ou outra forma de filiação ao INSS?",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["aposentadoria", "incapacidade", "salario-maternidade"],
      previous: "general-inss-request",
      next: "general-recent-event",
      active: true,
      order: 30,
    },
    {
      id: "general-recent-event",
      slug: "evento-recente",
      version: 1,
      title:
        "Existe alguma data, evento ou mudança recente relacionada ao caso?",
      description: "Não é necessário anexar documentos nesta etapa.",
      type: "radio",
      required: false,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown"],
      benefits: ["salario-maternidade", "incapacidade", "pensao"],
      previous: "general-affiliation",
      next: "general-documents-available",
      active: true,
      order: 40,
    },
    {
      id: "general-documents-available",
      slug: "documentos-disponiveis",
      version: 1,
      title:
        "Há documentos ou informações que poderão ser apresentados posteriormente?",
      description:
        "Não solicite upload nem informe dados completos de terceiros.",
      type: "radio",
      required: false,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown"],
      benefits: ["aposentadoria", "incapacidade", "assistencial"],
      previous: "general-recent-event",
      active: true,
      order: 50,
    },
  ],
  rules: [
    {
      ruleKey: "general-retirement-interest",
      ruleType: "topic",
      benefitSlug: "aposentadoria",
      active: true,
      priority: 10,
      conditions: [
        {
          questionId: "general-main-situation",
          operator: "equals",
          value: "retirement",
          score: 55,
          reason: "Tema de aposentadoria informado.",
        },
        {
          questionId: "general-affiliation",
          operator: "equals",
          value: "yes",
          score: 20,
          reason: "Histórico de filiação ao INSS informado.",
        },
      ],
    },
    {
      ruleKey: "general-disability-interest",
      ruleType: "topic",
      benefitSlug: "incapacidade",
      active: true,
      priority: 20,
      conditions: [
        {
          questionId: "general-main-situation",
          operator: "equals",
          value: "disability",
          score: 55,
          reason: "Tema de benefício por incapacidade informado.",
        },
        {
          questionId: "general-inss-request",
          operator: "equals",
          value: "denied",
          score: 20,
          reason: "Pedido negado informado.",
        },
      ],
    },
    {
      ruleKey: "general-maternity-interest",
      ruleType: "topic",
      benefitSlug: "salario-maternidade",
      active: true,
      priority: 30,
      conditions: [
        {
          questionId: "general-main-situation",
          operator: "equals",
          value: "maternity",
          score: 70,
          reason: "Tema de salário-maternidade informado.",
        },
      ],
    },
    {
      ruleKey: "general-assistance-interest",
      ruleType: "topic",
      benefitSlug: "assistencial",
      active: true,
      priority: 40,
      conditions: [
        {
          questionId: "general-main-situation",
          operator: "equals",
          value: "bpc",
          score: 60,
          reason: "Tema de BPC/LOAS informado.",
        },
        {
          questionId: "general-main-situation",
          operator: "equals",
          value: "dependent_disability",
          score: 40,
          reason: "Tema relacionado a dependente com deficiência informado.",
        },
      ],
    },
  ],
};

export const maternityQuizTemplate: QuizTemplateDefinition = {
  id: "22222222-2222-4222-8222-222222222222",
  slug: "salario-maternidade",
  name: "Triagem de salário-maternidade",
  description:
    "Organiza informações preliminares relacionadas a salário-maternidade.",
  category: "beneficio",
  audience:
    "Pessoas com situação relacionada a nascimento, adoção ou evento equiparado.",
  type: "maternity",
  source: "platform",
  ownership: "platform_managed",
  status: "active",
  version: 1,
  isDefault: false,
  completenessFields: [
    "maternity-related-situation",
    "maternity-work-status",
    "maternity-inss-request",
  ],
  preventiveText: platformPreventiveText,
  result: {
    title: "Informações relacionadas a salário-maternidade organizadas",
    summary:
      "Suas respostas organizaram informações relacionadas a salário-maternidade. A análise adequada pode depender da categoria de segurada, histórico contributivo, data do evento e documentação.",
    nextStep:
      "O escritório poderá verificar quais documentos e informações complementares são necessários para avaliar a situação.",
    topicLabel: "Salário-maternidade",
  },
  questions: [
    {
      id: "maternity-related-situation",
      slug: "situacao-salario-maternidade",
      version: 1,
      title: "Qual situação está relacionada ao pedido?",
      type: "radio",
      required: true,
      options: [
        { value: "birth", label: "Nascimento" },
        { value: "adoption", label: "Adoção" },
        {
          value: "judicial_guard",
          label: "Guarda judicial para fins de adoção",
        },
        { value: "non_criminal_abortion", label: "Aborto não criminoso" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["salario-maternidade"],
      next: "maternity-event-timing",
      active: true,
      order: 10,
    },
    {
      id: "maternity-event-timing",
      slug: "data-evento-salario-maternidade",
      version: 1,
      title: "Qual foi ou será a data aproximada do evento?",
      description:
        "Informe apenas a situação geral. A data exata e documentos podem ser avaliados depois.",
      type: "radio",
      required: false,
      options: [
        { value: "already_happened", label: "Já ocorreu" },
        { value: "will_happen", label: "Ainda não ocorreu" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["salario-maternidade"],
      previous: "maternity-related-situation",
      next: "maternity-work-status",
      active: true,
      order: 20,
    },
    {
      id: "maternity-work-status",
      slug: "situacao-trabalho-salario-maternidade",
      version: 1,
      title:
        "Na época do evento, qual era a sua situação de trabalho ou contribuição?",
      type: "radio",
      required: true,
      options: [
        { value: "employee", label: "Empregada com carteira" },
        { value: "domestic_worker", label: "Trabalhadora doméstica" },
        { value: "individual_taxpayer", label: "Contribuinte individual" },
        { value: "mei", label: "MEI" },
        { value: "optional_insured", label: "Segurada facultativa" },
        { value: "rural_worker", label: "Trabalhadora rural" },
        { value: "unemployed", label: "Desempregada" },
        { value: "other", label: "Outra" },
      ],
      answerStateOptions: ["unknown"],
      benefits: ["salario-maternidade"],
      previous: "maternity-event-timing",
      next: "maternity-recent-contributions",
      active: true,
      order: 30,
    },
    {
      id: "maternity-recent-contributions",
      slug: "contribuicoes-recentes",
      version: 1,
      title: "Houve contribuições recentes ao INSS?",
      type: "radio",
      required: false,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["salario-maternidade"],
      previous: "maternity-work-status",
      next: "maternity-inss-request",
      active: true,
      order: 40,
    },
    {
      id: "maternity-inss-request",
      slug: "pedido-inss-salario-maternidade",
      version: 1,
      title: "Já houve pedido no INSS?",
      type: "radio",
      required: true,
      options: [
        { value: "not_requested", label: "Não" },
        { value: "pending", label: "Em análise" },
        { value: "approved", label: "Aprovado" },
        { value: "denied", label: "Negado" },
      ],
      answerStateOptions: ["unknown"],
      benefits: ["salario-maternidade"],
      previous: "maternity-recent-contributions",
      next: "maternity-denial-reason",
      active: true,
      order: 50,
    },
    {
      id: "maternity-denial-reason",
      slug: "motivo-negativa-salario-maternidade",
      version: 1,
      title: "Em caso de negativa, existe informação sobre o motivo?",
      type: "radio",
      required: false,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "not_applicable"],
      benefits: ["salario-maternidade"],
      previous: "maternity-inss-request",
      active: true,
      order: 60,
    },
  ],
  rules: [
    {
      ruleKey: "maternity-topic",
      ruleType: "topic",
      benefitSlug: "salario-maternidade",
      active: true,
      priority: 10,
      conditions: [
        {
          questionId: "maternity-related-situation",
          operator: "exists",
          score: 35,
          reason: "Situação relacionada ao evento informada.",
        },
        {
          questionId: "maternity-work-status",
          operator: "exists",
          score: 25,
          reason: "Categoria de trabalho ou contribuição informada.",
        },
        {
          questionId: "maternity-inss-request",
          operator: "equals",
          value: "denied",
          score: 25,
          reason: "Negativa do INSS informada.",
        },
      ],
    },
  ],
};

export const fibromyalgiaQuizTemplate: QuizTemplateDefinition = {
  id: "33333333-3333-4333-8333-333333333333",
  slug: "fibromialgia",
  name: "Triagem relacionada à fibromialgia",
  description:
    "Organiza informações preliminares sobre impactos funcionais relatados, sem diagnóstico ou conclusão de incapacidade.",
  category: "saude",
  audience: "Pessoas que relatam fibromialgia ou acompanhamento relacionado.",
  type: "fibromyalgia",
  source: "platform",
  ownership: "platform_managed",
  status: "active",
  version: 1,
  isDefault: false,
  completenessFields: [
    "fibromyalgia-diagnosis-context",
    "fibromyalgia-functional-impact",
    "fibromyalgia-documents",
  ],
  preventiveText: platformPreventiveText,
  result: {
    title: "Informações sobre limitações relatadas foram organizadas",
    summary:
      "As respostas indicam um tema que pode exigir análise individual das limitações relatadas, do histórico contributivo, das atividades exercidas e da documentação disponível. A existência de uma condição de saúde, isoladamente, não confirma direito a benefício.",
    nextStep:
      "O atendimento humano poderá avaliar histórico, documentos e contexto individual, sem que esta triagem confirme incapacidade.",
    topicLabel: "Tema relacionado à fibromialgia",
  },
  questions: [
    {
      id: "fibromyalgia-diagnosis-context",
      slug: "contexto-fibromialgia",
      version: 1,
      title:
        "Você informa possuir diagnóstico ou acompanhamento relacionado à fibromialgia?",
      description:
        "Não informe detalhes médicos, laudos ou exames nesta etapa.",
      type: "radio",
      required: true,
      options: [
        {
          value: "professional_diagnosis",
          label: "Possuo diagnóstico informado por profissional de saúde",
        },
        {
          value: "under_investigation",
          label: "Estou em investigação ou acompanhamento",
        },
        { value: "no_diagnosis", label: "Não possuo diagnóstico" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["fibromialgia", "incapacidade", "assistencial"],
      next: "fibromyalgia-functional-impact",
      metadata: { sensitive: true },
      active: true,
      order: 10,
    },
    {
      id: "fibromyalgia-functional-impact",
      slug: "impacto-funcional-fibromialgia",
      version: 1,
      title: "A condição tem afetado suas atividades habituais ou de trabalho?",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "partial", label: "Parcialmente" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["fibromialgia", "incapacidade"],
      previous: "fibromyalgia-diagnosis-context",
      next: "fibromyalgia-limitation-duration",
      metadata: { sensitive: true },
      active: true,
      order: 20,
    },
    {
      id: "fibromyalgia-limitation-duration",
      slug: "tempo-limitacao-fibromialgia",
      version: 1,
      title: "Há quanto tempo essa limitação é percebida?",
      type: "radio",
      required: false,
      options: [
        { value: "less_than_3_months", label: "Menos de 3 meses" },
        { value: "3_to_6_months", label: "Entre 3 e 6 meses" },
        { value: "6_to_12_months", label: "Entre 6 e 12 meses" },
        { value: "more_than_12_months", label: "Mais de 12 meses" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["fibromialgia", "incapacidade"],
      previous: "fibromyalgia-functional-impact",
      next: "fibromyalgia-current-care",
      metadata: { sensitive: true },
      active: true,
      order: 30,
    },
    {
      id: "fibromyalgia-current-care",
      slug: "acompanhamento-fibromialgia",
      version: 1,
      title: "Existe acompanhamento médico atual?",
      type: "radio",
      required: false,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["fibromialgia"],
      previous: "fibromyalgia-limitation-duration",
      next: "fibromyalgia-documents",
      metadata: { sensitive: true },
      active: true,
      order: 40,
    },
    {
      id: "fibromyalgia-documents",
      slug: "documentos-fibromialgia",
      version: 1,
      title:
        "Existem relatórios, exames, receitas ou outros registros que poderão ser apresentados posteriormente?",
      description: "Não envie nem transcreva conteúdo dos documentos agora.",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["fibromialgia", "incapacidade", "assistencial"],
      previous: "fibromyalgia-current-care",
      next: "fibromyalgia-inss-history",
      metadata: { sensitive: true },
      active: true,
      order: 50,
    },
    {
      id: "fibromyalgia-inss-history",
      slug: "historico-inss-fibromialgia",
      version: 1,
      title: "Houve afastamento do trabalho ou pedido no INSS?",
      type: "radio",
      required: false,
      options: [
        { value: "leave_without_request", label: "Afastamento sem pedido" },
        { value: "pending_request", label: "Pedido em análise" },
        { value: "approved_request", label: "Pedido aprovado" },
        { value: "denied_request", label: "Pedido negado" },
        { value: "ceased_benefit", label: "Benefício cessado" },
        { value: "none", label: "Não houve" },
      ],
      answerStateOptions: ["unknown"],
      benefits: ["fibromialgia", "incapacidade"],
      previous: "fibromyalgia-documents",
      active: true,
      order: 60,
    },
  ],
  rules: [
    {
      ruleKey: "fibromyalgia-functional-topic",
      ruleType: "topic",
      benefitSlug: "fibromialgia",
      active: true,
      priority: 10,
      conditions: [
        {
          questionId: "fibromyalgia-functional-impact",
          operator: "equals",
          value: "yes",
          score: 35,
          reason: "Impacto funcional informado.",
        },
        {
          questionId: "fibromyalgia-documents",
          operator: "equals",
          value: "yes",
          score: 25,
          reason: "Documentos avaliáveis poderão ser apresentados.",
        },
        {
          questionId: "fibromyalgia-inss-history",
          operator: "equals",
          value: "denied_request",
          score: 20,
          reason: "Pedido negado informado.",
        },
      ],
    },
  ],
};

export const depressionQuizTemplate: QuizTemplateDefinition = {
  id: "44444444-4444-4444-8444-444444444444",
  slug: "depressao",
  name: "Triagem relacionada à depressão",
  description:
    "Organiza informações preliminares sobre impactos funcionais relacionados à saúde mental, sem avaliar diagnóstico ou gravidade clínica.",
  category: "saude",
  audience:
    "Pessoas que informam acompanhamento ou impactos relacionados à saúde mental.",
  type: "depression",
  source: "platform",
  ownership: "platform_managed",
  status: "active",
  version: 1,
  isDefault: false,
  completenessFields: [
    "depression-care-context",
    "depression-functional-impact",
    "depression-documents",
  ],
  preventiveText: platformPreventiveText,
  result: {
    title: "Informações de saúde mental foram organizadas para triagem",
    summary:
      "As informações fornecidas podem ser relevantes para uma análise previdenciária individualizada. A ferramenta não avalia diagnóstico, gravidade clínica ou incapacidade e não substitui avaliação médica ou jurídica.",
    nextStep:
      "O escritório poderá avaliar o contexto previdenciário com apoio de documentos e informações complementares, se você decidir prosseguir.",
    topicLabel: "Tema relacionado à depressão",
  },
  questions: [
    {
      id: "depression-care-context",
      slug: "acompanhamento-saude-mental",
      version: 1,
      title: "Você informa estar em acompanhamento relacionado à saúde mental?",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
        { value: "seeking_care", label: "Estou buscando acompanhamento" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["depressao", "incapacidade"],
      next: "depression-diagnosis-info",
      metadata: { sensitive: true },
      active: true,
      order: 10,
    },
    {
      id: "depression-diagnosis-info",
      slug: "diagnostico-saude-mental",
      version: 1,
      title: "Há informação de diagnóstico por profissional de saúde?",
      description: "Não informe diagnóstico detalhado nesta etapa.",
      type: "radio",
      required: false,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
        { value: "under_investigation", label: "Em investigação" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["depressao", "incapacidade"],
      previous: "depression-care-context",
      next: "depression-functional-impact",
      metadata: { sensitive: true },
      active: true,
      order: 20,
    },
    {
      id: "depression-functional-impact",
      slug: "impacto-rotina-trabalho-saude-mental",
      version: 1,
      title: "A situação tem afetado suas atividades de trabalho ou rotina?",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "partial", label: "Parcialmente" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["depressao", "incapacidade"],
      previous: "depression-diagnosis-info",
      next: "depression-work-leave",
      metadata: { sensitive: true },
      active: true,
      order: 30,
    },
    {
      id: "depression-work-leave",
      slug: "afastamento-trabalho-saude-mental",
      version: 1,
      title: "Existe afastamento do trabalho?",
      type: "radio",
      required: false,
      options: [
        { value: "currently_away", label: "Atualmente afastado" },
        { value: "previously_away", label: "Já estive afastado" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["not_applicable", "withheld"],
      benefits: ["depressao", "incapacidade"],
      previous: "depression-functional-impact",
      next: "depression-inss-request",
      metadata: { sensitive: true },
      active: true,
      order: 40,
    },
    {
      id: "depression-inss-request",
      slug: "pedido-inss-saude-mental",
      version: 1,
      title: "Houve pedido no INSS?",
      type: "radio",
      required: false,
      options: [
        { value: "pending", label: "Em análise" },
        { value: "approved", label: "Aprovado" },
        { value: "denied", label: "Negado" },
        { value: "ceased", label: "Cessado" },
        { value: "none", label: "Não houve" },
      ],
      answerStateOptions: ["unknown"],
      benefits: ["depressao", "incapacidade"],
      previous: "depression-work-leave",
      next: "depression-documents",
      active: true,
      order: 50,
    },
    {
      id: "depression-documents",
      slug: "documentos-saude-mental",
      version: 1,
      title: "Existem documentos que poderão ser avaliados posteriormente?",
      description: "Não transcreva conteúdo médico nesta etapa.",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["depressao", "incapacidade"],
      previous: "depression-inss-request",
      metadata: { sensitive: true },
      active: true,
      order: 60,
    },
  ],
  rules: [
    {
      ruleKey: "depression-functional-topic",
      ruleType: "topic",
      benefitSlug: "depressao",
      active: true,
      priority: 10,
      conditions: [
        {
          questionId: "depression-functional-impact",
          operator: "equals",
          value: "yes",
          score: 35,
          reason: "Impacto em rotina ou trabalho informado.",
        },
        {
          questionId: "depression-documents",
          operator: "equals",
          value: "yes",
          score: 25,
          reason: "Documentos avaliáveis poderão ser apresentados.",
        },
        {
          questionId: "depression-inss-request",
          operator: "equals",
          value: "denied",
          score: 20,
          reason: "Pedido negado informado.",
        },
      ],
    },
  ],
};

export const autismQuizTemplate: QuizTemplateDefinition = {
  id: "55555555-5555-4555-8555-555555555555",
  slug: "autismo",
  name: "Triagem relacionada ao autismo",
  description:
    "Organiza informações para análise relacionada a BPC, dependentes e outros temas pertinentes, sem solicitar dados completos de terceiro.",
  category: "saude-familia",
  audience:
    "Pessoas que buscam organizar informações sobre si, filho, dependente ou pessoa sob responsabilidade.",
  type: "autism",
  source: "platform",
  ownership: "platform_managed",
  status: "active",
  version: 1,
  isDefault: false,
  completenessFields: [
    "autism-person-context",
    "autism-support-needs",
    "autism-family-income-info",
  ],
  preventiveText: platformPreventiveText,
  result: {
    title: "Informações relacionadas ao autismo foram organizadas",
    summary:
      "As respostas organizaram informações que podem ser relevantes para uma avaliação individual. A existência de diagnóstico não confirma, por si só, direito a benefício. A análise pode depender da situação da pessoa, necessidade de apoio, contexto familiar, renda e documentação.",
    nextStep:
      "O escritório poderá avaliar o contexto familiar, documentos disponíveis e informações complementares sem que esta triagem conclua direito a benefício.",
    topicLabel: "Tema relacionado ao autismo",
  },
  questions: [
    {
      id: "autism-person-context",
      slug: "pessoa-relacionada-autismo",
      version: 1,
      title: "A situação se refere a quem?",
      type: "radio",
      required: true,
      options: [
        { value: "self", label: "A mim" },
        { value: "child", label: "Filho ou filha" },
        { value: "dependent", label: "Outro dependente" },
        {
          value: "person_under_responsibility",
          label: "Pessoa sob minha responsabilidade",
        },
      ],
      answerStateOptions: ["withheld"],
      benefits: ["autismo", "assistencial"],
      next: "autism-diagnosis-context",
      metadata: { sensitive: true },
      active: true,
      order: 10,
    },
    {
      id: "autism-diagnosis-context",
      slug: "contexto-diagnostico-autismo",
      version: 1,
      title:
        "Existe diagnóstico ou acompanhamento relacionado ao Transtorno do Espectro Autista?",
      description: "Não informe dados completos de terceiro nesta etapa.",
      type: "radio",
      required: true,
      options: [
        {
          value: "professional_diagnosis",
          label: "Diagnóstico informado por profissional",
        },
        { value: "under_investigation", label: "Em investigação" },
        {
          value: "care_without_diagnosis",
          label: "Acompanhamento sem diagnóstico informado",
        },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["autismo", "assistencial"],
      previous: "autism-person-context",
      next: "autism-support-needs",
      metadata: { sensitive: true },
      active: true,
      order: 20,
    },
    {
      id: "autism-support-needs",
      slug: "necessidade-apoio-autismo",
      version: 1,
      title: "A pessoa necessita de apoio em atividades da rotina?",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "partial", label: "Parcialmente" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["autismo", "assistencial"],
      previous: "autism-diagnosis-context",
      next: "autism-benefit-request",
      metadata: { sensitive: true },
      active: true,
      order: 30,
    },
    {
      id: "autism-benefit-request",
      slug: "pedido-beneficio-autismo",
      version: 1,
      title: "A família já solicitou algum benefício?",
      type: "radio",
      required: false,
      options: [
        { value: "bpc", label: "BPC/LOAS" },
        { value: "other_benefit", label: "Outro benefício" },
        { value: "pending", label: "Pedido em análise" },
        { value: "denied", label: "Pedido negado" },
        { value: "none", label: "Não houve pedido" },
      ],
      answerStateOptions: ["unknown"],
      benefits: ["autismo", "assistencial"],
      previous: "autism-support-needs",
      next: "autism-family-income-info",
      active: true,
      order: 40,
    },
    {
      id: "autism-family-income-info",
      slug: "informacoes-renda-familia-autismo",
      version: 1,
      title:
        "Há informações sobre renda e composição familiar disponíveis para avaliação posterior?",
      description:
        "Não informe renda detalhada ou dados completos de familiares neste primeiro contato.",
      type: "radio",
      required: true,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["autismo", "assistencial"],
      previous: "autism-benefit-request",
      next: "autism-documents",
      metadata: { sensitive: true },
      active: true,
      order: 50,
    },
    {
      id: "autism-documents",
      slug: "documentos-autismo",
      version: 1,
      title:
        "Existem relatórios ou registros de acompanhamento que poderão ser apresentados posteriormente?",
      description: "Não envie nem transcreva documentos nesta etapa.",
      type: "radio",
      required: false,
      options: [
        { value: "yes", label: "Sim" },
        { value: "no", label: "Não" },
      ],
      answerStateOptions: ["unknown", "withheld"],
      benefits: ["autismo", "assistencial"],
      previous: "autism-family-income-info",
      metadata: { sensitive: true },
      active: true,
      order: 60,
    },
  ],
  rules: [
    {
      ruleKey: "autism-assistance-topic",
      ruleType: "topic",
      benefitSlug: "autismo",
      active: true,
      priority: 10,
      conditions: [
        {
          questionId: "autism-support-needs",
          operator: "equals",
          value: "yes",
          score: 30,
          reason: "Necessidade de apoio informada.",
        },
        {
          questionId: "autism-family-income-info",
          operator: "equals",
          value: "yes",
          score: 20,
          reason: "Informações familiares poderão ser avaliadas.",
        },
        {
          questionId: "autism-benefit-request",
          operator: "equals",
          value: "denied",
          score: 25,
          reason: "Pedido negado informado.",
        },
      ],
    },
  ],
};

export const defaultQuizTemplates: QuizTemplateDefinition[] = [
  generalQuizTemplate,
  maternityQuizTemplate,
  fibromyalgiaQuizTemplate,
  depressionQuizTemplate,
  autismQuizTemplate,
];
