import type { BrandConfig } from "@/types/brand";

export const defaultBrandConfig: BrandConfig = {
  name: "Resende Advogados Associados",
  legalName: "Resende Advogados Associados",
  logo: "/brand/logo-placeholder.svg",
  favicon: "/favicon.ico",
  primaryColor: "#12312f",
  secondaryColor: "#0f766e",
  accentColor: "#b78b3b",
  backgroundColor: "#fbfaf7",
  foregroundColor: "#171717",
  buttonColor: "#12312f",
  buttonTextColor: "#ffffff",
  whatsappColor: "#166534",
  icon: undefined,
  socialImage: undefined,
  whatsapp: "5500000000000",
  whatsappDefaultMessage:
    "Olá! Acessei o Radar Previdenciário da Resende Advogados e gostaria de falar com a equipe.",
  phone: undefined,
  email: undefined,
  website: "https://radarprevidenciario.com.br",
  instagram: "",
  facebook: "",
  linkedin: "",
  youtube: "",
  tiktok: "",
  address: undefined,
  city: undefined,
  state: undefined,
  zipCode: undefined,
  cnpj: undefined,
  privacyEmail: undefined,
  supportEmail: undefined,
  copyright: "Todos os direitos reservados.",
  poweredBy: "Radar Previdenciário",
  shortContactText: undefined,
  institutionalMessage: undefined,
  registrationTitle: "Cadastro inicial",
  registrationSubtitle:
    "Preencha seus dados para iniciar uma triagem rápida e informativa.",
  registrationSupportText:
    "Leva poucos minutos. Ao final, você receberá uma orientação inicial sobre o seu caso.",
  registrationButtonLabel: "Iniciar minha triagem",
  registrationNamePlaceholder: "Informe seu nome e sobrenome",
  registrationEmailPlaceholder: "voce@email.com",
  registrationPhonePlaceholder: "(00) 00000-0000",
};
