import type { BrandConfig } from "@/types/brand";

export const defaultBrandConfig: BrandConfig = {
  name: "Resende Advogados Associados",
  legalName: "Resende Advogados Associados",
  logo: "/brand/logo-placeholder.svg",
  favicon: "/favicon.ico",
  primaryColor: "#12312f",
  secondaryColor: "#0f766e",
  accentColor: "#b78b3b",
  backgroundColor: "#fbfaf7",
  foregroundColor: "#171717",
  whatsapp: "5500000000000",
  whatsappDefaultMessage:
    "Olá, concluí a triagem informativa no Radar Previdenciário e gostaria de obter mais informações sobre os próximos passos.",
  phone: undefined,
  email: undefined,
  website: "https://radarprevidenciario.com.br",
  instagram: "",
  facebook: "",
  linkedin: "",
  youtube: "",
  tiktok: "",
  address: undefined,
  city: undefined,
  state: undefined,
  zipCode: undefined,
  cnpj: undefined,
  privacyEmail: undefined,
  supportEmail: undefined,
  copyright: "Todos os direitos reservados.",
  poweredBy: "Radar Previdenciário",
};
